# Generated by Django 4.2.3 on 2023-07-27 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='company_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='number',
            field=models.IntegerField(default=False),
        ),
    ]
