# Generated by Django 4.2.3 on 2023-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0002_detail_date_alter_detail_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='company_name',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
