# Generated by Django 4.2.3 on 2023-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0004_detail_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='product',
        ),
    ]
