# Generated by Django 4.2.3 on 2023-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0007_remove_detail_product_detail_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='product_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
