# Generated by Django 4.2.3 on 2023-07-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquire', '0008_alter_detail_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
